[phases.setup]
# We tell Nixpacks to pull the 'dart' package from the Nix repository
nixPkgs = ["dart"]

[phases.install]
# We run 'dart pub get' in the install phase
cmds = ["dart pub get"]

[phases.build]
# If you are deploying Flutter Web, we build it here
cmds = ["flutter build web --release"]

[start]
# If you're serving the build via a Go server (recommended)
cmd = "./main"